name: zoom_clone
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

#  cloud_firestore:
  cloud_firestore: ^3.1.0
#  firebase_core:
#  To have UserCredential available, use firebase_core: "^1.7.0" and firebase_auth: "3.1.3"
  firebase_core: "^1.7.0"
  firebase_auth: "^3.1.3"

  #  For the sake of GoogleAuthProvider and .getCredential, use these dependencies: google_sign_in: ^4.0.1+1 firebase_auth: ^0.8.1+1
#  firebase_auth: ^0.8.1+1
#  google_sign_in: ^4.0.1+1
  google_sign_in: ^5.4.2
  cupertino_icons: ^1.0.2
  jitsi_meet:
  intl:
  flutter_launcher_icons: "^0.9.2"
  # flutter_native_splash: ^2.1.0





flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon-c.png"

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
      - assets/images/onboarding.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
